package sam.backup.manager.view.backup;

public enum Type {
	WILL_BE_ZIPPED,
	WILL_BE_COPIED, 
	STATE_CHANGED, 
	CHECKING_FILETREE, 
	START_ZIPPING_OPERATION, 
	START_ZIP_DIR, 
	SUCCCESS_ZIP_DIR, 
	FAILED_ZIP_DIR, 
	REMOVE_FROM_FILETREE, 
	ADD_TO_ZIP,
	ADDED_TO_ZIP,
	FILE_NOT_FOUND, 
	ALREADY_ZIPPED, 
	COMPLETED_ZIPPING_OPERATION, 
	START_FILE_COPY_OPERATION,
	COMPLETED_FILE_COPY_OPERATION,
	START_FILE_COPY, 
	SUCCCESS_FILE_COPY, 
	FAILED_FILE_COPY, 
	MOVING_ZIP, 
}
